// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Warehouse.Api.Data;

#nullable disable

namespace Warehouse.Api.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20250606185821_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Warehouse.Api.Entities.ReturnMerchandiseAuthorization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DistributionCenter")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReturnRequestId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ReturnMerchandiseAuthorization");
                });

            modelBuilder.Entity("Warehouse.Api.Entities.ReturnMerchandiseAuthorizationLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ArticleCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ReturnMerchandiseAuthorizationId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ReturnMerchandiseAuthorizationId");

                    b.ToTable("ReturnMerchandiseAuthorizationLines");
                });

            modelBuilder.Entity("Warehouse.Api.Entities.TrackAndTrace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ReturnMerchandiseAuthorizationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TrackAndTraceCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ReturnMerchandiseAuthorizationId");

                    b.ToTable("TrackAndTraces");
                });

            modelBuilder.Entity("Warehouse.Api.Entities.ReturnMerchandiseAuthorizationLine", b =>
                {
                    b.HasOne("Warehouse.Api.Entities.ReturnMerchandiseAuthorization", "ReturnMerchandiseAuthorization")
                        .WithMany("Lines")
                        .HasForeignKey("ReturnMerchandiseAuthorizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReturnMerchandiseAuthorization");
                });

            modelBuilder.Entity("Warehouse.Api.Entities.TrackAndTrace", b =>
                {
                    b.HasOne("Warehouse.Api.Entities.ReturnMerchandiseAuthorization", "ReturnMerchandiseAuthorization")
                        .WithMany("TrackAndTraces")
                        .HasForeignKey("ReturnMerchandiseAuthorizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReturnMerchandiseAuthorization");
                });

            modelBuilder.Entity("Warehouse.Api.Entities.ReturnMerchandiseAuthorization", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("TrackAndTraces");
                });
#pragma warning restore 612, 618
        }
    }
}
